name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt update && sudo apt install -y build-essential git wget openjdk-17-jdk

      - run: git clone https://github.com/Stephane-D/SGDK.git

      - run: java -jar SGDK/bin/rescomp.jar res/resources.res

      - run: make -f SGDK/makefile.gen

      - uses: actions/upload-artifact@v4
        with:
          name: rom
          path: out/*.bin
