name: SGDK Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential openjdk-17-jdk

      - name: Clone SGDK
        run: git clone https://github.com/Stephane-D/SGDK.git $HOME/SGDK

      - name: Set SGDK environment
        run: |
          echo "GDK=$HOME/SGDK" >> $GITHUB_ENV
          echo "$HOME/SGDK/bin" >> $GITHUB_PATH

      - name: Build game
        run: |
          make clean
          make -f $HOME/SGDK/makefile.gen

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: sgdk-rom
          path: "*.bin"
